name: Deploy Function to Firebase

on:
  push:
    branches:
      - master-functions

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Build App
        working-directory: ./functions
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: Functions
          path: functions/lib

  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact Functions
        uses: actions/download-artifact@master
        with:
          name: Functions
          path: functions/lib
      - name: Deploy Functions to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only function
        env:
          PROJECT_ID: ${{ secrets.FIREBASE_PROJEKT_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: '/home/runner/work/dashboard/dashboard'
